{% set name = "napari-plugin-manager" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 371d93914bc4ba5185b0d5da40b1747a386bfe9fc681408f4e0b0cfb81e2fa59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.8
    - npe2
    - qtpy
    - superqt
    - pip
    # - napari >=0.4.18

test:
  imports:
    - napari_plugin_manager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/napari/napari-plugin-manager
  summary: Install plugins for napari, in napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
